AWSTemplateFormatVersion: 2010-09-09
Description: Deploy an ECS cluster running Jenkins with a persistent data store

Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      - Label:
          default: ECS Details
        Parameters:
          - ClusterName
          - ImageURL
      - Label:
          default: Network Details
        Parameters:
          - VpcId
          - PublicSubnet1
          - PublicSubnet2
          - PrivateSubnet1
          - PrivateSubnet2
          - CertificateArn
      - Label:
          default: If you'd like to scale the cluster down in an evening, specify the scale in and out times below in hh:mm format
        Parameters:
          - ScaleOutTime
          - ScaleInTime
      - Label:
          default: Specify domain name (e.g. example.com) and domain name (e.g. jenkins.example.com) if you want to update Route53
        Parameters:
          - DomainName
          - DomainRecord

Parameters:
  ClusterName:
    Type: String
    Description: Name for ECS Jenkins Cluster
    Default: JenkinsCluster
  ImageURL:
    Type: String
    Description: URL for Jenkins Image
    Default: docker.io/jenkins/jenkins
  CertificateArn:
    Type: String
    AllowedPattern: '^.+$'
    Description: ARN of an existing certificate which will be attached to the ALB created by the stack, to serve HTTPS traffic (mandatory).
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC for Jenkins Deployment
  PublicSubnet1:
    Type: AWS::EC2::Subnet::Id
    Description: First Public Subnet for deployment
  PublicSubnet2:
    Type: AWS::EC2::Subnet::Id
    Description: Second Public Subnet for deployment
  PrivateSubnet1:
    Type: AWS::EC2::Subnet::Id
    Description: First Private Subnet for deployment
  PrivateSubnet2:
    Type: AWS::EC2::Subnet::Id
    Description: Second Private Subnet for deployment
  ScaleOutTime:
    Type: String
    Description: Time to scale out (optional but should be in 24 hour hh:mm format if specified)
    Default: ""
    AllowedPattern: ^$|^[0-2]\d:[0-5]\d$
  ScaleInTime:
    Type: String
    Description: Time to scale in (optional but should be in 24 hour hh:mm format if specified)
    Default: ""
    AllowedPattern: ^$|^[0-2]\d:[0-5]\d$
  DomainName:
    Type: String
    Description: Route53 Hosted Zone Domain to add CNAME to (e.g. example.com), or blank string for no DNS updates
    Default: ""
    AllowedPattern: ^$|^[a-zA-Z0-9][a-zA-Z0-9-]*\.[a-zA-Z]+\.$
  DomainRecord:
    Type: String
    Description: Name for CNAME record pointing to ALB, or blank string for no DNS updates
    Default: ""

Conditions:
  ScheduleSpecified: !And
    - !Not 
      - !Equals [ !Ref ScaleOutTime, ""]
    - !Not 
      - !Equals [ !Ref ScaleInTime, ""]

  Route53Update: !And
    - !Not 
      - !Equals [ !Ref DomainName, ""]
    - !Not 
      - !Equals [ !Ref DomainRecord, ""]

Resources:
# Security Groups -------------------------------------------------------------
  JenkinsLBSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for Jenkins LoadBalancer
      VpcId:            !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol:   tcp
          Description:  Allow incoming access on port 8080
          FromPort:     443
          ToPort:       443
          CidrIp:       0.0.0.0/0

  JenkinsSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for Jenkins instances
      VpcId:            !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol:             tcp
          Description:            Allow incoming access on port 8080 from JenkinsLB
          FromPort:               8080
          ToPort:                 8080
          SourceSecurityGroupId:  !Ref JenkinsLBSG

  JenkinsEFSSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for Jenkins EFS Data volume
      VpcId:            !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol:             tcp
          Description:            EFS Access
          FromPort:               2049
          ToPort:                 2049
          SourceSecurityGroupId:  !Ref JenkinsSG

# EFS Resources ---------------------------------------------------------------
  JenkinsDataVol:
    Type: AWS::EFS::FileSystem
    Properties:
      Encrypted: true
      FileSystemTags:
        - Key: Name
          Value: JenkinsDataVol

  JenkinsDataVolAccessPoint:
    Type: AWS::EFS::AccessPoint
    Properties:
      FileSystemId: !Ref JenkinsDataVol
      PosixUser:
        Uid: '1000'
        Gid: '1000'
      RootDirectory:
        CreationInfo:
          OwnerGid: '1000'
          OwnerUid: '1000'
          Permissions: '755'
        Path: '/jenkins-home'

  JenkinsDataVolMountTargetSnA:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref JenkinsDataVol
      SecurityGroups:
        - !Ref JenkinsEFSSG
      SubnetId: !Ref PrivateSubnet1

  JenkinsDataVolMountTargetSnB:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref JenkinsDataVol
      SecurityGroups:
        - !Ref JenkinsEFSSG
      SubnetId: !Ref PrivateSubnet2

# Log Group -------------------------------------------------------------------
  JenkinsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/jenkinsECS
      RetentionInDays: 3

# IAM Roles -------------------------------------------------------------------
  JenkinsExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  JenkinsTaskRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - elasticfilesystem:ClientMount
                  - elasticfilesystem:ClientWrite
                Resource: !GetAtt JenkinsDataVol.Arn

  JenkinsAutoscalingRole:
    Type: AWS::IAM::Role
    Condition: ScheduleSpecified
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: application-autoscaling.amazonaws.com
      Policies:
        - PolicyName: ECS_Autoscaling
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - application-autoscaling:*
                  - ecs:DescribeServices
                  - ecs:UpdateService
                Resource: '*'

# ECS Resources ---------------------------------------------------------------
  JenkinsCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref ClusterName
      CapacityProviders:
        - FARGATE_SPOT

  JenkinsTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Volumes:
        - Name: jenkins-home
          EFSVolumeConfiguration:
            FilesystemId: !Ref JenkinsDataVol
            TransitEncryption: ENABLED
            AuthorizationConfig:
              AccessPointId: !Ref JenkinsDataVolAccessPoint
              IAM: ENABLED
      ContainerDefinitions:
        - Name: JenkinsInstance
          Image: !Ref ImageURL
          MountPoints:
            - SourceVolume:   jenkins-home
              ContainerPath:  /var/jenkins_home
              ReadOnly:       false
          PortMappings:
            - ContainerPort: 8080
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref 'AWS::Region'
              awslogs-group: !Ref JenkinsLogGroup
              awslogs-stream-prefix: ecsJenkins
      RequiresCompatibilities:
        - FARGATE
      Cpu:    '512'
      Memory: '1024'
      NetworkMode: awsvpc
      TaskRoleArn: !Ref JenkinsTaskRole
      ExecutionRoleArn: !Ref JenkinsExecutionRole

  JenkinsService:
    Type: AWS::ECS::Service
    DependsOn: LoadBalancerListener
    Properties:
      Cluster: !Ref JenkinsCluster
      TaskDefinition: !Ref JenkinsTaskDefinition
      DesiredCount: 1
      HealthCheckGracePeriodSeconds: 300
      LaunchType: FARGATE
      DeploymentConfiguration:
        MinimumHealthyPercent: 0
        MaximumPercent: 100
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref PublicSubnet1
            - !Ref PublicSubnet2
          SecurityGroups:
            - !GetAtt JenkinsSG.GroupId
      LoadBalancers:
        - ContainerName: JenkinsInstance
          ContainerPort: 8080
          TargetGroupArn: !Ref JenkinsTargetGroup


# LoadBalancer Resources ------------------------------------------------------
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      SecurityGroups:
        - !Ref JenkinsLBSG

  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !Ref CertificateArn
      DefaultActions:
        - Type: forward
          ForwardConfig:
            TargetGroups:
              - TargetGroupArn: !Ref JenkinsTargetGroup
      LoadBalancerArn: !Ref LoadBalancer

  JenkinsTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckPath: /login
      Port: 8080
      Protocol: HTTP
      TargetType: ip
      VpcId: !Ref VpcId


# Autoscaling Schedule --------------------------------------------------------
  ServiceScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Condition: ScheduleSpecified
    Properties:
      MinCapacity: 0
      MaxCapacity: 1
      ServiceNamespace: ecs
      ScalableDimension: ecs:service:DesiredCount
      ResourceId: !Join [
        "/", [
          "service",
          !Ref JenkinsCluster,
          !GetAtt JenkinsService.Name
        ]
      ]
      RoleARN: !GetAtt JenkinsAutoscalingRole.Arn
      ScheduledActions:
        - Schedule: !Sub
          - "cron(${mm} ${hh} * * ? *)"
          - mm: !Select [ 1, !Split [ ":", !Ref ScaleOutTime ]]
            hh: !Select [ 0, !Split [ ":", !Ref ScaleOutTime ]]
          ScheduledActionName: increaseSchedule
          ScalableTargetAction: 
            MinCapacity: 1
            MaxCapacity: 1
        - Schedule: !Sub
          - "cron(${mm} ${hh} * * ? *)"
          - mm: !Select [ 1, !Split [ ":", !Ref ScaleInTime ]]
            hh: !Select [ 0, !Split [ ":", !Ref ScaleInTime ]]
          ScheduledActionName: decreaseSchedule
          ScalableTargetAction: 
            MinCapacity: 0
            MaxCapacity: 0       


# Route53 Update --------------------------------------------------------------
  R53LBName:
    Type: AWS::Route53::RecordSet
    Condition: Route53Update
    Properties:
      HostedZoneName: !Ref DomainName
      Type:           CNAME
      Name:           !Ref DomainRecord
      TTL:            300
      ResourceRecords:
        - !GetAtt LoadBalancer.DNSName

