AWSTemplateFormatVersion: 2010-09-09
Description: Deploy an ECS cluster running Jenkins with a persistent data store

Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups:
      - Label:
          default: ECS Details
        Parameters:
          - pClusterName
          - pContainerName
          - pImageURL
      - Label:
          default: Network Details
        Parameters:
          - pVpcId
          - pPublicSubnet1
          - pPublicSubnet2
          - pPrivateSubnet1
          - pPrivateSubnet2
          - pCertificateArn
      - Label:
          default: If you'd like to scale the cluster down in an evening, specify the scale in and out times below in hh:mm format
        Parameters:
          - pScaleOutTime
          - pScaleInTime
      - Label:
          default: Specify domain name (e.g. example.com) and domain name (e.g. jenkins.example.com) if you want to update Route53
        Parameters:
          - pDomainName
          - pDomainRecord

Parameters:
  pClusterName:
    Type: String
    Description: Name for ECS Jenkins Cluster
    Default: JenkinsCluster
  pContainerName:
    Type: String
    Description: Name for Container within ECS Task Definition
    Default: JenkinsContainer
  pImageURL:
    Type: String
    Description: URL for Jenkins Image
    Default: docker.io/jenkins/jenkins
  pCertificateArn:
    Type: String
    AllowedPattern: '^.+$'
    Description: ARN of an existing certificate which will be attached to the ALB created by the stack, to serve HTTPS traffic (mandatory).
  pVpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC for Jenkins Deployment
  pPublicSubnet1:
    Type: AWS::EC2::Subnet::Id
    Description: First Public Subnet for deployment
  pPublicSubnet2:
    Type: AWS::EC2::Subnet::Id
    Description: Second Public Subnet for deployment
  pPrivateSubnet1:
    Type: AWS::EC2::Subnet::Id
    Description: First Private Subnet for deployment
  pPrivateSubnet2:
    Type: AWS::EC2::Subnet::Id
    Description: Second Private Subnet for deployment
  pScaleOutTime:
    Type: String
    Description: Time to scale out (optional but should be in 24 hour hh:mm format if specified)
    Default: ""
    AllowedPattern: ^$|^[0-2]\d:[0-5]\d$
  pScaleInTime:
    Type: String
    Description: Time to scale in (optional but should be in 24 hour hh:mm format if specified)
    Default: ""
    AllowedPattern: ^$|^[0-2]\d:[0-5]\d$
  pDomainName:
    Type: String
    Description: Route53 Hosted Zone Domain to add CNAME to (e.g. example.com), or blank string for no DNS updates
    Default: ""
    AllowedPattern: ^$|^[a-zA-Z0-9][a-zA-Z0-9-]*\.[a-zA-Z]+\.$
  pDomainRecord:
    Type: String
    Description: Name for CNAME record pointing to ALB, or blank string for no DNS updates
    Default: ""

Conditions:
  cScheduleSpecified: !And
    - !Not 
      - !Equals [ !Ref pScaleOutTime, ""]
    - !Not 
      - !Equals [ !Ref pScaleInTime, ""]

  cRoute53Update: !And
    - !Not 
      - !Equals [ !Ref pDomainName, ""]
    - !Not 
      - !Equals [ !Ref pDomainRecord, ""]

Resources:
# Security Groups -------------------------------------------------------------
  rJenkinsLBSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for Jenkins LoadBalancer
      VpcId:            !Ref pVpcId
      SecurityGroupIngress:
        - IpProtocol:   tcp
          Description:  Allow incoming access on port 8080
          FromPort:     443
          ToPort:       443
          CidrIp:       0.0.0.0/0

  rJenkinsSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for Jenkins instances
      VpcId:            !Ref pVpcId
      SecurityGroupIngress:
        - IpProtocol:             tcp
          Description:            Allow incoming access on port 8080 from JenkinsLB
          FromPort:               8080
          ToPort:                 8080
          SourceSecurityGroupId:  !Ref rJenkinsLBSG

  rJenkinsEFSSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for Jenkins EFS Data volume
      VpcId:            !Ref pVpcId
      SecurityGroupIngress:
        - IpProtocol:             tcp
          Description:            EFS Access
          FromPort:               2049
          ToPort:                 2049
          SourceSecurityGroupId:  !Ref rJenkinsSG

# EFS Resources ---------------------------------------------------------------
  rJenkinsDataVol:
    Type: AWS::EFS::FileSystem
    Properties:
      Encrypted: true
      FileSystemTags:
        - Key: Name
          Value: JenkinsDataVol

  rJenkinsDataVolAccessPoint:
    Type: AWS::EFS::AccessPoint
    Properties:
      FileSystemId: !Ref rJenkinsDataVol
      PosixUser:
        Uid: '1000'
        Gid: '1000'
      RootDirectory:
        CreationInfo:
          OwnerGid: '1000'
          OwnerUid: '1000'
          Permissions: '755'
        Path: '/jenkins-home'

  rJenkinsDataVolMountTargetSnA:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref rJenkinsDataVol
      SecurityGroups:
        - !Ref rJenkinsEFSSG
      SubnetId: !Ref pPrivateSubnet1

  rJenkinsDataVolMountTargetSnB:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref rJenkinsDataVol
      SecurityGroups:
        - !Ref rJenkinsEFSSG
      SubnetId: !Ref pPrivateSubnet2

# Log Group -------------------------------------------------------------------
  rJenkinsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/ecs/${pClusterName}"
      RetentionInDays: 3

# IAM Roles -------------------------------------------------------------------
  rJenkinsExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  rJenkinsTaskRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - elasticfilesystem:ClientMount
                  - elasticfilesystem:ClientWrite
                Resource: !GetAtt rJenkinsDataVol.Arn

  rJenkinsAutoscalingRole:
    Type: AWS::IAM::Role
    Condition: cScheduleSpecified
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: application-autoscaling.amazonaws.com
      Policies:
        - PolicyName: ECS_Autoscaling
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - application-autoscaling:*
                  - ecs:DescribeServices
                  - ecs:UpdateService
                Resource: '*'

# ECS Resources ---------------------------------------------------------------
  rJenkinsCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref pClusterName
      CapacityProviders:
        - FARGATE_SPOT

  rJenkinsTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Volumes:
        - Name: jenkins-home
          EFSVolumeConfiguration:
            FilesystemId: !Ref rJenkinsDataVol
            TransitEncryption: ENABLED
            AuthorizationConfig:
              AccessPointId: !Ref rJenkinsDataVolAccessPoint
              IAM: ENABLED
      ContainerDefinitions:
        - Name: !Ref pContainerName
          Image: !Ref pImageURL
          MountPoints:
            - SourceVolume:   jenkins-home
              ContainerPath:  /var/jenkins_home
              ReadOnly:       false
          PortMappings:
            - ContainerPort: 8080
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref 'AWS::Region'
              awslogs-group: !Ref rJenkinsLogGroup
              awslogs-stream-prefix: ecsJenkins
      RequiresCompatibilities:
        - FARGATE
      Cpu:    '512'
      Memory: '1024'
      NetworkMode: awsvpc
      TaskRoleArn: !Ref rJenkinsTaskRole
      ExecutionRoleArn: !Ref rJenkinsExecutionRole

  rJenkinsService:
    Type: AWS::ECS::Service
    DependsOn: rLoadBalancerListener
    Properties:
      Cluster: !Ref rJenkinsCluster
      TaskDefinition: !Ref rJenkinsTaskDefinition
      DesiredCount: 1
      HealthCheckGracePeriodSeconds: 300
      LaunchType: FARGATE
      DeploymentConfiguration:
        MinimumHealthyPercent: 0
        MaximumPercent: 100
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref pPublicSubnet1
            - !Ref pPublicSubnet2
          SecurityGroups:
            - !GetAtt rJenkinsSG.GroupId
      LoadBalancers:
        - ContainerName: !Ref pContainerName
          ContainerPort: 8080
          TargetGroupArn: !Ref rJenkinsTargetGroup


# LoadBalancer Resources ------------------------------------------------------
  rLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Subnets:
        - !Ref pPublicSubnet1
        - !Ref pPublicSubnet2
      SecurityGroups:
        - !Ref rJenkinsLBSG

  rLoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !Ref pCertificateArn
      DefaultActions:
        - Type: forward
          ForwardConfig:
            TargetGroups:
              - TargetGroupArn: !Ref rJenkinsTargetGroup
      LoadBalancerArn: !Ref rLoadBalancer

  rJenkinsTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckPath: /login
      Port: 8080
      Protocol: HTTP
      TargetType: ip
      VpcId: !Ref pVpcId


# Autoscaling Schedule --------------------------------------------------------
  rServiceScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Condition: cScheduleSpecified
    Properties:
      MinCapacity: 0
      MaxCapacity: 1
      ServiceNamespace: ecs
      ScalableDimension: ecs:service:DesiredCount
      ResourceId: !Join [
        "/", [
          "service",
          !Ref rJenkinsCluster,
          !GetAtt rJenkinsService.Name
        ]
      ]
      RoleARN: !GetAtt rJenkinsAutoscalingRole.Arn
      ScheduledActions:
        - Schedule: !Sub
          - "cron(${mm} ${hh} * * ? *)"
          - mm: !Select [ 1, !Split [ ":", !Ref pScaleOutTime ]]
            hh: !Select [ 0, !Split [ ":", !Ref pScaleOutTime ]]
          ScheduledActionName: increaseSchedule
          ScalableTargetAction: 
            MinCapacity: 1
            MaxCapacity: 1
        - Schedule: !Sub
          - "cron(${mm} ${hh} * * ? *)"
          - mm: !Select [ 1, !Split [ ":", !Ref pScaleInTime ]]
            hh: !Select [ 0, !Split [ ":", !Ref pScaleInTime ]]
          ScheduledActionName: decreaseSchedule
          ScalableTargetAction: 
            MinCapacity: 0
            MaxCapacity: 0       


# Route53 Update --------------------------------------------------------------
  rR53LBName:
    Type: AWS::Route53::RecordSet
    Condition: cRoute53Update
    Properties:
      HostedZoneName: !Ref pDomainName
      Type:           CNAME
      Name:           !Ref pDomainRecord
      TTL:            300
      ResourceRecords:
        - !GetAtt rLoadBalancer.DNSName

